version: '3.9'

service:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    enviroment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db-data: