---
- name: Publish secrets to Kubernetes Cluster
  hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Copy k8s secrets from ansible host to the master nodes.
      copy: 
        src: secrets/k8s-secrets.yaml
        dest: /home/ubuntu/secrets.yaml
        mode: 0777
    - name: Apply secrets
      shell: sudo kubectl apply -f /home/ubuntu/secrets.yaml
