---
- name: Delete secrets to Kubernetes Cluster
  hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Delete secrets
      shell: sudo kubectl delete -f /home/ubuntu/secrets.yaml
    - name: Delete secrets file
      shell: sudo rm -rf /home/ubuntu/secrets.yaml