---
- name: Deploy debug pod
  hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Copy k8s deployment specification from ansible host to the master nodes.
      copy:
        src: k8s-debug/
        dest: /home/ubuntu/debug-manifest/
        mode: 0777
    - name: Create a Deployment for the debug pod
      shell: sudo kubectl apply -f /home/ubuntu/debug-manifest/deploy.yaml