---
- name: "Delete the debug deployment on Kubernetes Cluster"
  hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Delete deployment
      shell: sudo kubectl delete -f /home/ubuntu/debug-manifest/
    - name: Delete source files
      shell: sudo rm -rf /home/ubuntu/debug-manifest/