apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
spec:
  template:
    spec:
      containers:
      - name: init-container
        image: postgres:14
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: dbuser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: dbpassword
        command: ["/bin/sh", "-c"]
        args:
        - |
          export PGPASSWORD=$POSTGRES_PASSWORD
          for script in /scripts/*.sql; do
            psql -h db.default.svc.cluster.local -U $POSTGRES_USER -d $POSTGRES_DB -f $script
          done
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: script-volume
        configMap:
          name: db-init-scripts
  backoffLimit: 4  # Retries in case the job fails