apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual # provisioning is done manually
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany # multiple pods can read/write
  hostPath:
    path: /data/postgresql