apiVersion: v1
kind: Secret
metadata:
    name: regcred
type: Opaque
data:
    docker-server: "${PLACEHOLDER_B64_CONTAINERREGISTRYSERVER}"
    docker-username: "${PLACEHOLDER_B64_CONTAINERREGISTRYUSERNAME}"
    docker-password: "${PLACEHOLDER_B64_CONTAINERREGISTRYPASSWORD}"
    docker-email: "${PLACEHOLDER_B64_CONTAINERREGISTRYEMAIL}"
---
apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
type: Opaque
data:
    dbname: "${PLACEHOLDER_B64_DBNAME}"
    dbuser: "${PLACEHOLDER_B64_DBUSER}"
    dbpassword: "${PLACEHOLDER_B64_DBPASSWORD}"
    #dburl: "${PLACEHOLDER_B64_DBURL}"
---
# apiVersion: v1
# kind: Secret
# metadata:
#     name: harbor-secrets
# type: Opaque
# data:
#     HARBOR_ADMIN_PASSWORD: "${PLACEHOLDER_B64_HARBORPASSWORD}"
#     HARBOR_SECRET_KEY: "${PLACEHOLDER_B64_HARBORSECRETKEY}"
