---
- name: "Take Down Docker Containers for Database"
  hosts: db
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "Stop Docker Container for Database"
      shell: "docker stop postgres-db"
    - name: "Remove Docker Container for Database"
      shell: "docker rm postgres-db"
    - name: "Remove Docker Image for Database"
      shell: "docker rmi postgres:14"
    - name: "Remove Database Initialization Files"
      shell: "rm -rf /home/ubuntu/db"
    - name: "Remove Directory for Database Data"
      shell: "rm -rf /home/ubuntu/db-data"

- name: "Take Down Docker Containers for Storage Device"
  hosts: storage
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "Stop Docker Container for Storage Device"
      shell: "docker stop storage-device"
    - name: "Remove Docker Container for Storage Device"
      shell: "docker rm storage-device"
    - name: "Remove Docker Image for Storage Device"
      shell: "docker rmi {{ CONTAINER_REGISTRY_PREFIX }}:storage-device_latest"

- name: "Take Down Docker Containers for Backend Services"
  hosts: be
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "Stop Docker Container for Backend Services"
      shell: "docker stop be-{{ inventory_hostname[:-1] }} || true"
    - name: "Remove Docker Container for Backend Services"
      shell: "docker rm be-{{ inventory_hostname[:-1] }} || true"
    - name: "Remove Docker Image for Backend Services"
      shell: "docker rmi {{ CONTAINER_REGISTRY_PREFIX }}:be-{{ inventory_hostname[:-1] }}_latest || true"

- name: "Take Down Docker Containers for Frontend Services"
  hosts: fe
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "Stop Docker Container for Frontend Services"
      shell: "docker stop frontend"
    - name: "Remove Docker Container for Frontend Services"
      shell: "docker rm frontend"
    - name: "Remove Docker Image for Frontend Services"
      shell: "docker rmi {{ CONTAINER_REGISTRY_PREFIX }}:fe_latest"