---
- name: "Deploy Database Docker Container"
  hosts: db
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - "{{ playbook_dir }}/vars.yml"
  tasks:
    - name: "Pull Docker Image for Database"
      shell: "docker pull postgres:14"
    - name: "Copy Database Initialization Files"
      copy:
        src: "../db/"
        dest: "/home/ubuntu/db"
        owner: ubuntu
        group: ubuntu
        mode: '0755'
    - name: "Create Directory for Database Data"
      file:
        path: "/home/ubuntu/db-data"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
    - name: "Run Docker Container for Database"
      shell: |
        docker run -d \
          --name postgres-db \
          --restart always \
          -e POSTGRES_USER={{ db_user }} \
          -e POSTGRES_PASSWORD={{ db_password }} \
          -e POSTGRES_DB={{ db_name }} \
          -p 5432:5432 \
          -v /home/ubuntu/db-data/:/var/lib/postgresql/data/ \
          -v /home/ubuntu/db/:/docker-entrypoint-initdb.d/ \
          {% for host in groups['internal_targets'] %}
          --add-host={{ hostvars[host]['inventory_hostname'] }}:{{ hostvars[host].ansible_host }} \
          {% endfor %}
          postgres:14

- name: "Deploy Storage Device Docker Container"
  hosts: storage
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - "{{ playbook_dir }}/vars.yml"
  vars:
    storage_device_remote_image: "{{ rmcicd_int }}:5000/agisit24-g10_storage-device:latest"
  tasks:
    - name: "Pull Docker Image for Storage Device"
      shell: "docker --config /home/ubuntu/.docker pull {{ storage_device_remote_image }}"
    - name: "Docker Image Processing"
      shell: |
        docker inspect --format {{'{{.Id}}'}} {{ storage_device_remote_image }} > /home/ubuntu/running-image.id
        docker tag {{ storage_device_remote_image }} storage-device:latest
        docker rmi {{ storage_device_remote_image }}
    - name: "Run Docker Container for Storage Device"
      shell: |
        docker run -d \
          --name storage-device \
          --restart always \
          -p 5000:5000 \
          -e DB_URL=postgresql://{{ db_user }}:{{ db_password }}@db1_int:5432/{{ db_name }} \
          {% for host in groups['internal_targets'] %}
          --add-host={{ hostvars[host]['inventory_hostname'] }}:{{ hostvars[host].ansible_host }} \
          {% endfor %}
          storage-device:latest

- name: "Deploy Backend Carbs Docker Container"
  hosts: carbs
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - "{{ playbook_dir }}/vars.yml"
  vars:
    be_carbs_remote_image: "{{ rmcicd_int }}:5000/agisit24-g10_be-carbs:latest"
  tasks:
    - name: "Pull Docker Image for Backend Carbs"
      shell: "docker --config /home/ubuntu/.docker pull {{ be_carbs_remote_image }}"
    - name: "Docker Image Processing"
      shell: |
        docker inspect --format {{'{{.Id}}'}} {{ be_carbs_remote_image }} > /home/ubuntu/running-image.id
        docker tag {{ be_carbs_remote_image }} be-carbs:latest
        docker rmi {{ be_carbs_remote_image }}
    - name: "Run Docker Container for Backend Carbs"
      shell: |
        docker run -d \
          --name be-carbs \
          --restart always \
          -p 80:80 \
          -e STORAGE_DEVICE_URL=http://storage1_int:5000 \
          {% for host in groups['internal_targets'] %}
          --add-host={{ hostvars[host]['inventory_hostname'] }}:{{ hostvars[host].ansible_host }} \
          {% endfor %}
          be-carbs:latest

- name: "Deploy Backend Dairy Docker Container"
  hosts: dairy
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - "{{ playbook_dir }}/vars.yml"
  vars:
    be_dairy_remote_image: "{{ rmcicd_int }}:5000/agisit24-g10_be-dairy:latest"
  tasks:
    - name: "Pull Docker Image for Backend Dairy"
      shell: "docker --config /home/ubuntu/.docker pull {{ be_dairy_remote_image }}"
    - name: "Docker Image Processing"
      shell: |
        docker inspect --format {{'{{.Id}}'}} {{ be_dairy_remote_image }} > /home/ubuntu/running-image.id
        docker tag {{ be_dairy_remote_image }} be-dairy:latest
        docker rmi {{ be_dairy_remote_image }}
    - name: "Run Docker Container for Backend Dairy"
      shell: |
        docker run -d \
          --name be-dairy \
          --restart always \
          -p 80:80 \
          -e STORAGE_DEVICE_URL=http://storage1_int:5000 \
          {% for host in groups['internal_targets'] %}
          --add-host={{ hostvars[host]['inventory_hostname'] }}:{{ hostvars[host].ansible_host }} \
          {% endfor %}
          be-dairy:latest

- name: "Deploy Backend Meats Docker Container"
  hosts: meats
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - "{{ playbook_dir }}/vars.yml"
  vars:
    be_meats_remote_image: "{{ rmcicd_int }}:5000/agisit24-g10_be-meats:latest"
  tasks:
    - name: "Pull Docker Image for Backend Meats"
      shell: "docker --config /home/ubuntu/.docker pull {{ be_meats_remote_image }}"
    - name: "Docker Image Processing"
      shell: |
        docker inspect --format {{'{{.Id}}'}} {{ be_meats_remote_image }} > /home/ubuntu/running-image.id
        docker tag {{ be_meats_remote_image }} be-meats:latest
        docker rmi {{ be_meats_remote_image }}
    - name: "Run Docker Container for Backend Meats"
      shell: |
        docker run -d \
          --name be-meats \
          --restart always \
          -p 80:80 \
          -e STORAGE_DEVICE_URL=http://storage1_int:5000 \
          {% for host in groups['internal_targets'] %}
          --add-host={{ hostvars[host]['inventory_hostname'] }}:{{ hostvars[host].ansible_host }} \
          {% endfor %}
          be-meats:latest

- name: "Deploy Backend Vegetables Docker Container"
  hosts: vegetables
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - "{{ playbook_dir }}/vars.yml"
  vars:
    be_vegetables_remote_image: "{{ rmcicd_int }}:5000/agisit24-g10_be-vegetables:latest"
  tasks:
    - name: "Pull Docker Image for Backend Vegetables"
      shell: "docker --config /home/ubuntu/.docker pull {{ be_vegetables_remote_image }}"
    - name: "Docker Image Processing"
      shell: |
        docker inspect --format {{'{{.Id}}'}} {{ be_vegetables_remote_image }} > /home/ubuntu/running-image.id
        docker tag {{ be_vegetables_remote_image }} be-vegetables:latest
        docker rmi {{ be_vegetables_remote_image }}
    - name: "Run Docker Container for Backend Vegetables"
      shell: |
        docker run -d \
          --name be-vegetables \
          --restart always \
          -p 80:80 \
          -e STORAGE_DEVICE_URL=http://storage1_int:5000 \
          {% for host in groups['internal_targets'] %}
          --add-host={{ hostvars[host]['inventory_hostname'] }}:{{ hostvars[host].ansible_host }} \
          {% endfor %}
          be-vegetables:latest

- name: "Deploy Frontend Docker Container"
  hosts: fe
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - "{{ playbook_dir }}/vars.yml"
  vars:
    fe_remote_image: "{{ rmcicd_int }}:5000/agisit24-g10_fe:latest"
  tasks:
    - name: "Pull Docker Image for Frontend"
      shell: "docker --config /home/ubuntu/.docker pull {{ fe_remote_image }}"
    - name: "Docker Image Processing"
      shell: |
        docker inspect --format {{'{{.Id}}'}} {{ fe_remote_image }} > /home/ubuntu/running-image.id
        docker tag {{ fe_remote_image }} fe:latest
        docker rmi {{ fe_remote_image }}
    - name: "Run Docker Container for Frontend"
      shell: |
        docker run -d \
          --name frontend \
          --restart always \
          -p 80:80 \
          -e BE_CARBS_URL=http://carbs1_int:80 \
          -e BE_DAIRY_URL=http://dairy1_int:80 \
          -e BE_MEATS_URL=http://meats1_int:80 \
          -e BE_VEGETABLES_URL=http://vegetables1_int:80 \
          {% for host in groups['internal_targets'] %}
          --add-host={{ hostvars[host]['inventory_hostname'] }}:{{ hostvars[host].ansible_host }} \
          {% endfor %}
          fe:latest
